<a href="https://colab.research.google.com/github/trogtri/phantichdulieu/blob/main/lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sys
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
def load_data(filename):
  return pd.read_csv('https://raw.githubusercontent.com/huynhhoc/phantichdulieu/main/Data/covid19/'+filename)
dfcovid19 = load_data('countriessample.csv')
dfcovid19.head()

        Date   CountryRegion  Confirmed  Recovered  Deaths
0  1/22/2020    Ghana;Africa        NaN        NaN     0.0
1  1/22/2020   Greece;Europe        NaN        NaN     0.0
2  1/22/2020  Iceland;Europe        0.0        NaN     0.0
3  1/22/2020      India;Asia        0.0        NaN     0.0
4  1/22/2020  Indonesia;Asia        0.0        NaN     0.0